### ISSUE TITLE
ImageUtils always uses PNG for base64 conversion

### ISSUE THREAD

**Issue by laxika** [AoElite/claude4j#2]
As the title says:
https://github.com/AoElite/claude4j/blob/defb948d7600caf89759717a05415932fc1db90b/src/main/java/com/aoelite/claude/utils/ImageUtils.java#L23

I tried to upload JPG images but all of them failed. As soon as I converted them to PNG it worked.

Cool lib though! Thanks for making it public! ;)

**Comment by AoElite** [comment]
@laxika Should be fixed
